
[project]
name = "learning-rust-python"
version = "0.1.0"
description = "A Rust library for Python using Maturin and PyO3"
authors = [
  {name = "Tony Narlock", email = "tony@git-pull.com"}
]
license = { text = "All rights reserved." }
dependencies = []

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
# "extension-module" tells pyo3 we want to build an extension module (skips linking against libpython.so)
features = ["pyo3/extension-module"]